# Site settings
title: Spatial History of the Encyclopédie
tag_text: Space & the Encyclopédie
description: Research Project on Space and Place in the Encyclopédie
url: "http://127.0.0.1:4000"
baseurl: "kmcdono.com"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
